const CardData = [
  {
    id: "1",
    image: "images/food (1).jpeg",
    title: "Veg Mixer",
    desc: "Tomato Salad & Carrot",
    price: "$5.99",
    category: "Starters",
  },
  {
    id: "2",
    image: "images/food (2).jpeg",
    title: "Macaroni",
    desc: "Cheese Pizza",
    price: "$2.99",
    category: "Starters",
  },
  {
    id: "3",
    image: "images/food (3).jpeg",
    title: "Nelli",
    desc: "Hamburger & Fries",
    price: "$7.99",
    category: "Main",
  },
  {
    id: "4",
    image: "images/food (4).jpeg",
    title: "Japanio Poppers",
    desc: "Cripsy Soyabins",
    price: "$9.99",
    category: "Main",
  },
  {
    id: "5",
    image: "images/food (5).jpeg",
    title: "Cajun Chiken",
    desc: "Roasted Chicken & Ehgg",
    price: "$8.99",
    category: "Main",
  },
  {
    id: "6",
    image: "images/food (6).jpeg",
    title: "Chille Cake",
    desc: "Cheese Pizza",
    price: "$2.99",
    category: "Soup",
  },
  {
    id: "7",
    image: "images/food (7).jpeg",
    title: "Mutton Kacchi",
    desc: "Hamburger & Fries",
    price: "$7.99",
    category: "Soup",
  },
  {
    id: "8",
    image: "images/food (9).jpeg",
    title: "Rutoni Vaji",
    desc: "Cripsy Soyabins",
    price: "$9.99",
    category: "Desserts",
  },
];
export default CardData;
